### ISSUE TITLE
How to create files target.txt ,opinion.txt etc. located the Line 125 in the file read.py?

### ISSUE THREAD

**Issue by GitOffice** [XL2248/DREGCN#3]
As referred in your paper ,we employ the BIO tagging scheme: Yae={BA,IA,BP,IP,O}to label all the aspect and opinion terms.
Could you please upload the code snippet about BIO sequence labelling? 
I guess the code snippet can create files such as target.txt ,opinion.txt from restaurant laptop dataset.

**Comment by XL2248** [comment]
The dataset is from IMN (https://drive.google.com/file/d/1zp9fykp6_zPBBEiJp9zc8LKmXGfi2zDa/view)
